version: "3.8"
services:
  storage-management:
    image: filip/storage-management
    container_name: storage-management
    build:
      context: .
    ports:
      - 39009:9009
      - 38080:8080
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=8070"
    environment:
      KEYCLOAK_ADMIN: filip
      KEYCLOAK_ADMIN_PASSWORD: test
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak-lte:/opt/keycloak/data/import
    ports:
      - 38070:8070

volumes:
  keycloak-data: {}