spring:
  datasource:
    url: jdbc:h2:mem:store
    driverClassName: org.h2.Driver
    username: admin
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-client
            authorization-grant-type: authorization_code
            scope: openid
      provider:
        keycloak:
          issuer-uri: http://keycloak:8070/auth/realms/storage-management
          user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8070/realms/storage-management
server:
  port: 8080

